# Generated by Django 3.2 on 2021-04-16 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criou', models.DateTimeField(auto_now_add=True)),
                ('data_editou', models.DateTimeField(auto_now=True)),
                ('usuario_modificou', models.IntegerField(blank=True, null=True)),
                ('pais', models.CharField(max_length=100, unique=True)),
                ('ddi', models.CharField(max_length=3)),
                ('sigla', models.CharField(max_length=5)),
                ('usuario_criou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criou', models.DateTimeField(auto_now_add=True)),
                ('data_editou', models.DateTimeField(auto_now=True)),
                ('usuario_modificou', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('uf', models.CharField(max_length=2)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.pais')),
                ('usuario_criou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criou', models.DateTimeField(auto_now_add=True)),
                ('data_editou', models.DateTimeField(auto_now=True)),
                ('usuario_modificou', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=100, unique=True)),
                ('codigo_municipio', models.IntegerField(default=0, help_text='Necessário para emitir NFS-e.', verbose_name='Código Municipio (IBGE)')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bases.estado')),
                ('usuario_criou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
