# Generated by Django 3.2 on 2021-04-14 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='descricao',
            new_name='pais',
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criou', models.DateTimeField(auto_now_add=True)),
                ('data_editou', models.DateTimeField(auto_now=True)),
                ('usuario_modificou', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(max_length=100, unique=True)),
                ('usuario_criou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
    ]
