# Generated by Django 3.2 on 2021-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='ddi',
            field=models.CharField(max_length=4),
        ),
    ]
