# Generated by Django 3.2 on 2021-06-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0002_auto_20210602_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obraanexo',
            name='obra',
        ),
        migrations.AddField(
            model_name='obraanexo',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivo', to='bases.projeto'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projeto', to='bases.obra'),
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
