# Generated by Django 3.2 on 2021-04-16 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bases', '0002_auto_20210414_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criou', models.DateTimeField(auto_now_add=True)),
                ('data_editou', models.DateTimeField(auto_now=True)),
                ('usuario_modificou', models.IntegerField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=100, unique=True)),
                ('usuario_criou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
    ]
