# Generated by Django 3.2 on 2021-06-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0003_auto_20210602_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObraAnexo',
            new_name='ProjetoAnexo',
        ),
    ]
