# Generated by Django 3.2 on 2021-05-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_alter_arquivo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='status_obra',
            field=models.CharField(choices=[('EXE', 'Em execução'), ('FIN', 'Finalizada'), ('PAR', 'Paralizada')], max_length=3),
        ),
    ]
