# Generated by Django 3.2 on 2021-05-17 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0004_alter_arquivo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='arquivos_de_projeto/')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bases.projeto')),
            ],
        ),
    ]
