# Generated by Django 3.2 on 2021-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0005_alter_obra_status_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='codigo_municipio',
        ),
        migrations.AddField(
            model_name='cidade',
            name='cep',
            field=models.IntegerField(default=0, help_text='Somente números', verbose_name='Cep'),
        ),
    ]
