# Generated by Django 3.2 on 2021-05-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0006_auto_20210507_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cidade',
            name='cep',
        ),
        migrations.AddField(
            model_name='cidade',
            name='codigo_municipio',
            field=models.IntegerField(default=0, help_text='Necessário para emitir NFS-e.', verbose_name='Código Municipio (IBGE)'),
        ),
    ]
