# Generated by Django 3.2 on 2021-05-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0007_auto_20210510_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
